---
title: "HW 4"
author: "Robert Saldivar and Madeline Gorchels"
date: "5/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading neccessary packages

library(tidyverse)
library(deSolve)
library(sensitivity)

```

##Part 2: Run Model for 300 Years
```{r}
source("forest_growth.R")

initialforest = 100
#The function runs on it's own:
#forest_growth(initialC=initialforest, r=0.01, g=2, carry_capacity=500, air_temp=20, canopy_closure=100)

years = seq(from=1, to=300, by=1)
parms_1= list(initialC=initialforest, r=0.01, g=2, c_closure=100, carry_capacity=500, air_temp=20)

forest_1 = ode(y=initialforest, times=years, func=forest_growth,parms=parms_1)
forest_1

d_forest_1 = as.data.frame(forest_1) %>% 
  mutate(biomass=d_forest_1$`1`)


C_plot_1 = ggplot(d_forest_1)+
  geom_point(aes(x=time, y=biomass))+
  labs(y="Tree Biomass (kg C)", x="Years")+
  theme_classic()

C_plot_1
         
```

```{r}
# Setting the stage for the sobel sensitivity analysis

initialf = 10

np = 1000

#setting the first parameters
r = rnorm(mean = 0.01, sd = 0.0025, n = np)
g = rnorm(mean = 2, sd = 0.5, n=np)
x1 = cbind.data.frame(r=r, g=g)

#setting the second set of parameters
r = rnorm(mean = 0.01, sd = 0.0025, n = np)
g = rnorm(mean = 2, sd = 0.5, n=np)
x2 = cbind.data.frame(r=r, g=g)

sens_F = sobol2007(model = NULL, x1, x2, nboot = 300)

head(sens_F$X)

sens_F$X[1,]

initialf

simtimes = seq(from =1, to =300, by = 1)

parms = list(r=sens_F$X$r[1], g=sens_F$X$g[1])

result = ode(y = initialf, time=simtimes, parms = parms, func = forest_growth) # I am having trouble getting the ode solver to work


######################################################################

head(result)
colnames(result) = c("time", "C")

result = as.data.frame(result)
ggplot(result, aes(x= time, y = C)) +
  geom_point()



# Below this step, in this chunk might not be necessary for this hw
#Theis is determing when the forest reaches its maximum size
maxC = max(result$C)
maxC


#Determining when the max occurred
#maxtime = which.max(result$C)

#maxyear = result$time[idx]
#maxyear


```

```{r}

compute_metrics = function(result) {
  maxc = max(result$C)
  idx = which.max(result$C)
  maxyear = result$time[idx]
  return(list(maxC=maxC, maxyear = maxyear))
}

compute_metrics(result)

# create a wrapper for the function

wrapper = function(r, g, initialf, simtimes, func) {
  parms = list(r= r, g = g)
  result = ode(y= initialf, times = simtimes, func=forest_growth, parms = parms)
  #colnames(result = c("time", "C"))
  
  metrics=compute_metrics(as.data.frame(result))
  return(metrics)
}

allresults = mapply(FUN = wrapper, r=sens_F$X$r, g=sens_F$X$g, MoreArgs =list(initialf=initialf, simtimes=simtimes, func=forest_growth))

allres = as.data.frame(matrix(unlist(allresults), ncol=2, byrow = TRUE))
colname(allres) = c("maxC", "maxyear")

#this is for creating boxplots

box = allres %>%
  gather(key = "metric", value = "value")

ggplot(box, aes(metric, value, col=metric)) +
  geom_boxplot()

```

```{r}
#Computing the sobol indicies for each metric

#starting with the sensitivity for maxC
sens_F_maxC = sensitivity::tell(sens_F, allres$maxC)

sens_F_maxC$S

sens_F_maxC$T

plot(sens_F_maxC)

#Doing the Sensitivity for maxyear
sens_F_maxyear = sensitivity::tell(sens_F, allres$maxyear)

sens_F_maxyear$S

sens_F_maxyear$T

plot(sens_F_maxyear)

```

